import { MenuItem } from '@/types/menu';

export const initialMenu: MenuItem[] = [
    {
        key: 'cluster',
        title: '集群管理',
        icon: 'fa-solid fa-server',
        order: 1,
        children: [
            {
                key: 'multi_cluster',
                title: '多集群概览',
                icon: 'fa-solid fa-sitemap',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/multi_cluster")',
                order: 1,
            },
            {
                key: 'cluster_overview',
                title: '集群概览',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/summary_view")',
                order: 2,
            },
            {
                key: 'namespace',
                title: '命名空间',
                icon: 'fa-solid fa-folder',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/namespace")',
                order: 3,
            },
            {
                key: 'node',
                title: '节点',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/node")',
                order: 4,
            },
            {
                key: 'event',
                title: '事件',
                icon: 'fa-solid fa-calendar-alt',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/event")',
                order: 5,
            },
            {
                key: 'workload',
                title: '工作负载',
                icon: 'fa-solid fa-box',
                order: 6,
                children: [
                    {
                        key: 'deployment',
                        title: '部署',
                        icon: 'fa-solid fa-rocket',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/deployment")',
                        order: 1,
                    },
                    {
                        key: 'statefulset',
                        title: '有状态副本集',
                        icon: 'fa-solid fa-cubes',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/statefulset")',
                        order: 2,
                    },
                    {
                        key: 'daemonset',
                        title: '守护进程集',
                        icon: 'fa-solid fa-ghost',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/daemonset")',
                        order: 3,
                    },
                    {
                        key: 'job',
                        title: '任务',
                        icon: 'fa-solid fa-tasks',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/job")',
                        order: 4,
                    },
                    {
                        key: 'cronjob',
                        title: '定时任务',
                        icon: 'fa-solid fa-clock',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/cronjob")',
                        order: 5,
                    },
                    {
                        key: 'pod',
                        title: '容器组',
                        icon: 'fa-solid fa-box-open',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/pod")',
                        order: 6,
                    },
                    {
                        key: 'replicaset',
                        title: '副本集',
                        icon: 'fa-solid fa-copy',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/replicaset")',
                        order: 7,
                    },
                ],
            },
            {
                key: 'crd',
                title: '自定义资源',
                icon: 'fa-solid fa-puzzle-piece',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/crd")',
                order: 7,
            },
            {
                key: 'openkruise',
                title: 'OpenKruise',
                icon: 'fa-solid fa-wind',
                order: 8,
                show: 'isOpenKruiseSupported()',
                children: [
                    {
                        key: 'cloneset',
                        title: '克隆集',
                        icon: 'fa-solid fa-clone',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/cloneset")',
                        order: 1,
                    },
                    {
                        key: 'advanced_statefulset',
                        title: '高级有状态副本集',
                        icon: 'fa-solid fa-cubes',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/advanced_statefulset")',
                        order: 2,
                    },
                    {
                        key: 'advanced_daemonset',
                        title: '高级守护进程集',
                        icon: 'fa-solid fa-ghost',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/advanced_daemonset")',
                        order: 3,
                    },
                    {
                        key: 'broadcast_job',
                        title: '广播任务',
                        icon: 'fa-solid fa-bullhorn',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/broadcast_job")',
                        order: 4,
                    },
                    {
                        key: 'sidecarset',
                        title: '边车集',
                        icon: 'fa-solid fa-car-side',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/cluster/sidecarset")',
                        order: 5,
                    },
                ],
            },
            {
                key: 'istio',
                title: 'Istio',
                icon: 'fa-solid fa-wave-square',
                order: 9,
                show: 'isIstioSupported()',
                children: [
                    {
                        key: 'virtual_service',
                        title: '虚拟服务',
                        icon: 'fa-solid fa-compass',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/virtual_service")',
                        order: 1,
                    },
                    {
                        key: 'destination_rule',
                        title: '目标规则',
                        icon: 'fa-solid fa-map-signs',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/destination_rule")',
                        order: 2,
                    },
                    {
                        key: 'envoy_filter',
                        title: 'Envoy过滤器',
                        icon: 'fa-solid fa-filter',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/envoy_filter")',
                        order: 3,
                    },
                    {
                        key: 'gateway',
                        title: '网关',
                        icon: 'fa-solid fa-door-open',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/gateway")',
                        order: 4,
                    },
                    {
                        key: 'peer_authentication',
                        title: '对等认证',
                        icon: 'fa-solid fa-user-friends',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/peer_authentication")',
                        order: 5,
                    },
                    {
                        key: 'proxy_config',
                        title: '代理配置',
                        icon: 'fa-solid fa-cogs',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/proxy_config")',
                        order: 6,
                    },
                    {
                        key: 'request_authentication',
                        title: '请求认证',
                        icon: 'fa-solid fa-user-check',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/request_authentication")',
                        order: 7,
                    },
                    {
                        key: 'service_entry',
                        title: '服务入口',
                        icon: 'fa-solid fa-door-open',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/service_entry")',
                        order: 8,
                    },
                    {
                        key: 'sidecar',
                        title: '边车',
                        icon: 'fa-solid fa-car-side',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/sidecar")',
                        order: 9,
                    },
                    {
                        key: 'telemetry',
                        title: '遥测',
                        icon: 'fa-solid fa-chart-line',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/telemetry")',
                        order: 10,
                    },
                    {
                        key: 'authorization_policy',
                        title: '授权策略',
                        icon: 'fa-solid fa-user-shield',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/authorization_policy")',
                        order: 11,
                    },
                    {
                        key: 'wasm_plugin',
                        title: 'WASM插件',
                        icon: 'fa-solid fa-puzzle-piece',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/wasm_plugin")',
                        order: 12,
                    },
                    {
                        key: 'workload_entry',
                        title: '工作负载入口',
                        icon: 'fa-solid fa-door-open',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/workload_entry")',
                        order: 13,
                    },
                    {
                        key: 'workload_group',
                        title: '工作负载组',
                        icon: 'fa-solid fa-users',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/workload_group")',
                        order: 14,
                    },
                ],
            },
        ],
    },
    {
        key: 'helm',
        title: 'Helm',
        icon: 'fa-solid fa-ship',
        order: 2,
        children: [
            {
                key: 'repository',
                title: '仓库',
                icon: 'fa-solid fa-warehouse',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/helm/repository")',
                order: 1,
            },
            {
                key: 'chart',
                title: '包',
                icon: 'fa-solid fa-box',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/helm/chart")',
                order: 2,
            },
            {
                key: 'release',
                title: '发布',
                icon: 'fa-solid fa-rocket',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/helm/release")',
                order: 3,
            },
        ],
    },
    {
        key: 'config',
        title: '配置',
        icon: 'fa-solid fa-cog',
        order: 3,
        children: [
            {
                key: 'configmap',
                title: '配置项',
                icon: 'fa-solid fa-file-alt',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/configmap")',
                order: 1,
            },
            {
                key: 'secret',
                title: '密钥',
                icon: 'fa-solid fa-key',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/secret")',
                order: 2,
            },
            {
                key: 'webhook',
                title: 'webhook',
                icon: 'fa-solid fa-bell-concierge',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/webhook")',
                order: 3,
            },
        ],
    },
    {
        key: 'network',
        title: '网络',
        icon: 'fa-solid fa-network-wired',
        order: 4,
        children: [
            {
                key: 'service',
                title: '服务',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/service")',
                order: 1,
            },
            {
                key: 'ingress',
                title: '路由',
                icon: 'fa-solid fa-route',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/ingress")',
                order: 2,
            },
            {
                key: 'gateway_api',
                title: 'Gateway API',
                icon: 'fa-solid fa-door-open',
                order: 3,
                show: 'isGatewayAPISupported()',
                children: [
                    {
                        key: 'httproute',
                        title: 'HTTP路由',
                        icon: 'fa-solid fa-route',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/httproute")',
                        order: 1,
                    },
                    {
                        key: 'grpcroute',
                        title: 'GRPC路由',
                        icon: 'fa-solid fa-route',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/grpcroute")',
                        order: 2,
                    },
                    {
                        key: 'tcproute',
                        title: 'TCP路由',
                        icon: 'fa-solid fa-route',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/tcproute")',
                        order: 3,
                    },
                    {
                        key: 'udproute',
                        title: 'UDP路由',
                        icon: 'fa-solid fa-route',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/udproute")',
                        order: 4,
                    },
                    {
                        key: 'tlsroute',
                        title: 'TLS路由',
                        icon: 'fa-solid fa-route',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/tlsroute")',
                        order: 5,
                    },
                    {
                        key: 'referencegrant',
                        title: '引用授权',
                        icon: 'fa-solid fa-file-contract',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/ns/referencegrant")',
                        order: 6,
                    },
                ],
            },
        ],
    },
    {
        key: 'storage',
        title: '存储',
        icon: 'fa-solid fa-database',
        order: 5,
        children: [
            {
                key: 'persistent_volume',
                title: '持久卷',
                icon: 'fa-solid fa-hdd',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/persistent_volume")',
                order: 1,
            },
            {
                key: 'persistent_volume_claim',
                title: '持久卷声明',
                icon: 'fa-solid fa-hdd',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/persistent_volume_claim")',
                order: 2,
            },
            {
                key: 'storage_class',
                title: '存储类',
                icon: 'fa-solid fa-database',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/storage_class")',
                order: 3,
            },
        ],
    },
    {
        key: 'access_control',
        title: '访问控制',
        icon: 'fa-solid fa-user-shield',
        order: 6,
        children: [
            {
                key: 'service_account',
                title: '服务账户',
                icon: 'fa-solid fa-user',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/service_account")',
                order: 1,
            },
            {
                key: 'role',
                title: '角色',
                icon: 'fa-solid fa-user-tag',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/role")',
                order: 2,
            },
            {
                key: 'cluster_role',
                title: '集群角色',
                icon: 'fa-solid fa-user-tag',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/cluster_role")',
                order: 3,
            },
            {
                key: 'role_binding',
                title: '角色绑定',
                icon: 'fa-solid fa-link',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/role_binding")',
                order: 4,
            },
            {
                key: 'cluster_role_binding',
                title: '集群角色绑定',
                icon: 'fa-solid fa-link',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/cluster_role_binding")',
                order: 5,
            },
        ],
    },
    {
        key: 'cluster_config',
        title: '集群配置',
        icon: 'fa-solid fa-cogs',
        order: 7,
        children: [
            {
                key: 'namespace',
                title: '命名空间',
                icon: 'fa-solid fa-folder',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/namespace")',
                order: 1,
            },
            {
                key: 'endpoint',
                title: '端点',
                icon: 'fa-solid fa-ethernet',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/endpoint")',
                order: 2,
            },
            {
                key: 'endpointslice',
                title: '端点切片',
                icon: 'fa-solid fa-newspaper',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/endpointslice")',
                order: 3,
            },
            {
                key: 'hpa',
                title: '水平自动扩缩',
                icon: 'fa-solid fa-arrows-left-right',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/hpa")',
                order: 4,
            },
            {
                key: 'network_policy',
                title: '网络策略',
                icon: 'fa-solid fa-project-diagram',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/network_policy")',
                order: 5,
            },
            {
                key: 'resource_quota',
                title: '资源配额',
                icon: 'fa-solid fa-chart-pie',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/resource_quota")',
                order: 6,
            },
            {
                key: 'limit_range',
                title: '限制范围',
                icon: 'fa-solid fa-compress',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/limit_range")',
                order: 7,
            },
            {
                key: 'pdb',
                title: 'Pod中断配置',
                icon: 'fa-solid fa-receipt',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/pdb")',
                order: 8,
            },
            {
                key: 'lease',
                title: '租约',
                icon: 'fa-solid fa-file-contract',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/ns/lease")',
                order: 9,
            },
            {
                key: 'priority_class',
                title: '优先级类',
                icon: 'fa-solid fa-sort',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/priority_class")',
                order: 10,
            },
            {
                key: 'runtime_class',
                title: '运行时类',
                icon: 'fa-solid fa-play',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/runtime_class")',
                order: 11,
            },
            {
                key: 'csi_node',
                title: 'CSI节点',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/csi_node")',
                order: 12,
            },
            {
                key: 'api_service',
                title: 'API 服务',
                icon: 'fa-solid fa-code',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/api_service")',
                order: 13,
            },
            {
                key: 'flow_schema',
                title: '流量规则',
                icon: 'fa-solid fa-random',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/flow_schema")',
                order: 14,
            },
            {
                key: 'priority_level_config',
                title: '优先级配置',
                icon: 'fa-solid fa-sliders',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/priority_level_config")',
                order: 15,
            },
            {
                key: 'component_status',
                title: '组件状态',
                icon: 'fa-solid fa-info-circle',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/cluster/component_status")',
                order: 16,
            },
        ],
    },
    {
        key: 'platform_settings',
        title: '平台设置',
        icon: 'fa-solid fa-wrench',
        order: 8,
        show: 'isPlatformAdmin()',
        children: [
            {
                key: 'cluster_all',
                title: '多集群管理',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/cluster/cluster_all")',
                order: 1,
            },
            {
                key: 'system_config',
                title: '参数设置',
                icon: 'fa-solid fa-sliders',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/config/config")',
                order: 2,
            },
            {
                key: 'inspection_settings',
                title: '集群巡检设置',
                icon: 'fa-solid fa-stethoscope',
                order: 3,
                children: [
                    {
                        key: 'inspection_summary',
                        title: '巡检汇总',
                        icon: 'fa-solid fa-clipboard-list',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/admin/inspection/summary")',
                        order: 1,
                    },
                    {
                        key: 'inspection_schedule',
                        title: '巡检计划',
                        icon: 'fa-solid fa-stethoscope',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/admin/inspection/schedule")',
                        order: 2,
                    },
                    {
                        key: 'inspection_record',
                        title: '巡检记录',
                        icon: 'fa-solid fa-clipboard-list',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/admin/inspection/record")',
                        order: 3,
                    },
                    {
                        key: 'script_management',
                        title: '巡检规则',
                        icon: 'fa-solid fa-clipboard-check',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/admin/inspection/script")',
                        order: 4,
                    },
                    {
                        key: 'webhook_management',
                        title: 'webhook管理',
                        icon: 'fa-solid fa-bell-concierge',
                        eventType: 'custom',
                        customEvent: '() => loadJsonPage("/admin/inspection/webhook")',
                        order: 5,
                    },
                ],
            },
            {
                key: 'ai_model_config',
                title: 'AI模型配置',
                icon: 'fa-solid fa-sliders',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/config/ai_model_config")',
                order: 4,
            },
            {
                key: 'user_management',
                title: '用户管理',
                icon: 'fa-solid fa-user-gear',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/user/user")',
                order: 5,
            },
            {
                key: 'user_group_management',
                title: '用户组管理',
                icon: 'fa-solid fa-users-gear',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/user/user_group")',
                order: 6,
            },
            {
                key: 'mcp_management',
                title: 'MCP管理',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/mcp/mcp")',
                order: 7,
            },
            {
                key: 'mcp_tool_log',
                title: 'MCP执行记录',
                icon: 'fa-solid fa-history',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/mcp/mcp_log")',
                order: 8,
            },
            {
                key: 'condition_reverse',
                title: '指标显示翻转',
                icon: 'fa-solid fa-arrows-rotate',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/config/condition")',
                order: 9,
            },
            {
                key: 'sso_config',
                title: '单点登录',
                icon: 'fa-solid fa-right-to-bracket',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/admin/config/sso_config")',
                order: 10,
            },
        ],
    },
    {
        key: 'user_profile',
        title: '个人中心',
        icon: 'fa-solid fa-user',
        order: 9,
        children: [
            {
                key: 'user_profile_login_settings',
                title: '登录设置',
                icon: 'fa-solid fa-key',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/user/profile/login_settings")',
                order: 1,
            },
            {
                key: 'user_profile_clusters',
                title: '我的集群',
                icon: 'fa-solid fa-server',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/user/profile/my_clusters")',
                order: 2,
            },
            {
                key: 'user_profile_api_keys',
                title: 'API密钥',
                icon: 'fa-solid fa-key',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/user/profile/api_keys")',
                order: 3,
            },
            {
                key: 'user_profile_mcp_keys',
                title: '开放MCP',
                icon: 'fa-solid fa-share-nodes',
                eventType: 'custom',
                customEvent: '() => loadJsonPage("/user/profile/mcp_keys")',
                order: 4,
            },
        ],
    },
    {
        key: 'open_api',
        title: '开放API',
        icon: 'fa-solid fa-code-branch',
        eventType: 'custom',
        customEvent: '() => window.open("/swagger/index.html", "_blank")',
        order: 10,
    },
    {
        key: 'about',
        title: '关于 ',
        icon: 'fa-solid fa-circle-info',
        eventType: 'custom',
        customEvent: '() => loadJsonPage("/about/about")',
        order: 11,
    },
];